# Generated by Django 5.2.12 on 2026-03-26 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=100, null=True)),
                ('with_miltiq', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActiveRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activerole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blocked_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invite_link', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiamondBuyStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('amount', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diamondbuystars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.BigIntegerField()),
                ('phase', models.CharField(default='waiting', max_length=10)),
                ('mode', models.CharField(default='classic', max_length=20)),
                ('bot_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GamePhase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phase_type', models.CharField(max_length=10)),
                ('number', models.BigIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_end', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gamephase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=70)),
                ('is_alive', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now=True)),
                ('deaded_at', models.DateTimeField(auto_now=True)),
                ('is_sayed_last_word', models.BooleanField(default=False)),
                ('can_heal_self', models.BooleanField(default=True)),
                ('can_protection_self', models.BooleanField(default=True)),
                ('can_document_self', models.BooleanField(default=True)),
                ('can_investigate_self', models.BooleanField(default=True)),
                ('can_osishdan_himoya', models.BooleanField(default=True)),
                ('can_osishdan_himoya_adv', models.BooleanField(default=True)),
                ('can_slip_himoya', models.BooleanField(default=True)),
                ('is_sleep', models.BooleanField(default=False)),
                ('is_osilmas', models.BooleanField(default=False)),
                ('osildi', models.BooleanField(default=False)),
                ('missed_nights', models.BigIntegerField(default=0)),
                ('should_choose_card', models.BooleanField(default=False)),
                ('is_really_winner', models.BooleanField(default=False)),
                ('last_visited_user_id', models.BigIntegerField(null=True)),
                ('maxsus_raqam', models.BigIntegerField(null=True)),
                ('win', models.BooleanField(default=False)),
                ('is_actioned', models.BooleanField(default=False)),
                ('life', models.IntegerField(default=100)),
                ('team', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'gameplayer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GazabdorPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gazabdorpick',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('patron', models.IntegerField(default=10)),
                ('level', models.IntegerField(default=1)),
                ('himoya', models.IntegerField(default=0)),
                ('ball', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'geroys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeroyAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geroyaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('total_amount', models.BigIntegerField()),
                ('remaining_amount', models.BigIntegerField()),
                ('collected_users', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'giveaway',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GiveTopChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gived_at', models.DateTimeField(auto_now_add=True)),
                ('give_type', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'givetopchat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paralar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayersGameBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'playersgameball',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar', models.BigIntegerField(default=0)),
                ('diamond', models.BigIntegerField(default=0)),
                ('himoya', models.IntegerField(default=0)),
                ('hujjat', models.IntegerField(default=0)),
                ('qotildan_himoya', models.IntegerField(default=0)),
                ('osishdan_himoya', models.IntegerField(default=0)),
                ('miltiq', models.IntegerField(default=0)),
                ('doridan_himoya', models.IntegerField(default=0)),
                ('maska', models.IntegerField(default=0)),
                ('wins', models.BigIntegerField(default=0)),
                ('slip_himoya', models.IntegerField(default=0)),
                ('geroy_himoya', models.IntegerField(default=0)),
                ('games_count', models.BigIntegerField(default=0)),
                ('on_himoya', models.BooleanField(default=True)),
                ('on_hujjat', models.BooleanField(default=True)),
                ('on_qotildan_himoya', models.BooleanField(default=True)),
                ('on_osishdan_himoya', models.BooleanField(default=True)),
                ('on_miltiq', models.BooleanField(default=True)),
                ('on_doridan_himoya', models.BooleanField(default=True)),
                ('on_maska', models.BooleanField(default=True)),
                ('on_slip_himoya', models.BooleanField(default=True)),
                ('on_geroy_himoya', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('caption', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transfers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('full_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('mention', models.TextField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VipUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vipuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoteLike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_like', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'votelike',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransferPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cached_price', to='bot.transfer')),
            ],
            options={
                'db_table': 'transfer_price',
            },
        ),
    ]
